### ISSUE TITLE
How to solve package [teREVCOLolor] missing message , thanks

### ISSUE THREAD

**Issue by kidd6566** [megvii-research/RevCol#1]
Thanks for all your great work.

We've some error-message during Installation like below , and please give us more advice if any , thanks,
'''
ERROR: Could not find a version that satisfies the requirement teREVCOLolor==1.1.0 (from versions: none)
ERROR: No matching distribution found for  teREVCOLolor==1.1.0
'''

**Comment by nightsnack** [comment]
Hi kidd6566,
Sorry, my bad. It's a bug. it should be termcolor==1.1.0
Already fixed.

**Comment by kidd6566** [comment]
Hi Sir,

Sorry to bother you again.  Our Installation has been successfully made , thanks.

But there's another 'ERROR' when we're trying to finetune with *pre-trained weight* at this time.
Glad to have your suggestion if any , thanks in advance.

Btw , this ERROR won't be solved even we've installed 'dpflow' with PIP so far.

> Traceback (most recent call last):
>   File "main.py", line 33, in <module>
>     from data import build_loader
>   File "./RevCol/data/__init__.py", line 1, in <module>
>     from .build_data import build_loader
>   File "./RevCol/data/build_data.py", line 11, in <module>
>     from dpflow.pipe import InputPipe
> ModuleNotFoundError: No module named 'dpflow.pipe'

**Comment by nightsnack** [comment]
Hi,
These two lines should be deleted. It is connected with our private data server, which is unnecessary in this repo. Let me fix this. And I will double check all the files. Thanks for pointing out these bugs.
