### ISSUE TITLE
'tools/dist_train.sh'

### ISSUE THREAD

**Issue by 836469383** [megvii-research/RevCol#10]
First of all, I would say I think this is great work and I am very very interested. Then, I want to debug the segmentation task in the repository. But I didn't find the 'tools/dist_train.sh' when I followed the README.md. Any help will be appreciated.

**Comment by nightsnack** [comment]
Hi, 
just like that.
I will commit it to the repo later.

```
CONFIG=$1
GPUS=$2
NNODES=${NNODES:-1}
NODE_RANK=${NODE_RANK:-0}
PORT=${PORT:-29500}
MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}

torchrun \
    --nnodes=$NNODES \
    --master_addr=$MASTER_ADDR \
    --nproc_per_node=$GPUS \
    --master_port=$PORT \
    $(dirname "$0")/train.py \
    $CONFIG \
    --launcher pytorch ${@:3}
```

**Comment by 836469383** [comment]
Thanks for your answer. Best wishes.

**Comment by 836469383** [comment]
oh, when will you update the repo 030

**Comment by nightsnack** [comment]
> oh, when will you update the repo 030

Now.

**Comment by 836469383** [comment]
♥ & starred
