### ISSUE TITLE
你好，请问模型架构中的STEM的全称是什么？

### ISSUE THREAD

**Issue by tanganke** [megvii-research/RevCol#3]
你好，请问模型架构中的STEM的全称是什么，是什么意思？谢谢

**Comment by nightsnack** [comment]
STEM refers to the first convolution layer in CNN, similar to patch embedding in Transformer. Stem is not an abbreviation, it's original meaning refers to ’the main long thin part of a plant above the ground from which the leaves or flowers grow'.
