### ISSUE TITLE
对于语义分割部分的疑问

### ISSUE THREAD

**Issue by seaman1900** [megvii-research/RevCol#9]
作者你好，我拜读了您的论文，在语义分割部分是有multi scale的实验的，但是问题在于如果图片尺寸输入是某些奇数，比如说229或者223，那么上采样和下采样的部分就会不一致[x = self.up(c_up) + self.down(c_down](https://github.com/megvii-research/RevCol/blob/7a76c3902bacb3d05d4c2717e9d015bf1e561e93/models/revcol.py#L39)），我反复翻看了数据处理部分（mmsegmentaion中ade的config文件），并没有找到对这一错误的处理，于是想请教一下作者是如何处理这一部分的。

**Comment by nightsnack** [comment]
Hi,
You have to look in to the backbone code for segmentation (https://github.com/megvii-research/RevCol/blob/7a76c3902bacb3d05d4c2717e9d015bf1e561e93/Segmentation/mmseg/models/backbones/revcol_module.py#L21), you will find I use x = F.interpolate(x, shape, mode='nearest') in Upsample module to keep the resolution to be in consistent. Btw, I don't think preprocessing on data will solve this problem, and it may hurt accuracy.

**Comment by seaman1900** [comment]
> Hi,
> 
> You have to look in to the backbone code for segmentation (https://github.com/megvii-research/RevCol/blob/7a76c3902bacb3d05d4c2717e9d015bf1e561e93/Segmentation/mmseg/models/backbones/revcol_module.py#L21), you will find I use x = F.interpolate(x, shape, mode='nearest') in Upsample module to keep the resolution to be in consistent. Btw, I don't think preprocessing on data will solve this problem, and it may hurt accuracy.

- thanks！ that helps me a lot！i pay too much attention to the revcol model in the model/revcol.py file， thank you for your reminding agian！
